// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBth6Fj-IDemJxG1KDDRB1CxfRP3zURXX8',
    appId: '1:303368774121:web:87666e04c3796d8391eb78',
    messagingSenderId: '303368774121',
    projectId: 'chruchv2',
    authDomain: 'chruchv2.firebaseapp.com',
    storageBucket: 'chruchv2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhQ5N7RfYPJdu3xr3MJNqOYoqzkS44ZQE',
    appId: '1:303368774121:android:5c1623b3f437d09591eb78',
    messagingSenderId: '303368774121',
    projectId: 'chruchv2',
    storageBucket: 'chruchv2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMTEPMmQFYkK00IfGGR9lfzGZ5m818mt8',
    appId: '1:303368774121:ios:6e504f856860283691eb78',
    messagingSenderId: '303368774121',
    projectId: 'chruchv2',
    storageBucket: 'chruchv2.appspot.com',
    iosClientId: '303368774121-ja917h7oqkvtrp60cqedrhn4h99d7juu.apps.googleusercontent.com',
    iosBundleId: 'com.example.modernlogintute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMTEPMmQFYkK00IfGGR9lfzGZ5m818mt8',
    appId: '1:303368774121:ios:6e504f856860283691eb78',
    messagingSenderId: '303368774121',
    projectId: 'chruchv2',
    storageBucket: 'chruchv2.appspot.com',
    iosClientId: '303368774121-ja917h7oqkvtrp60cqedrhn4h99d7juu.apps.googleusercontent.com',
    iosBundleId: 'com.example.modernlogintute',
  );
}
